#!/bin/bash
# =============================================================================
# setup.sh — One-shot installer untuk VPS Scraper (browser project)
# Prasyarat: Ubuntu 22.04+ dengan Docker sudah terinstall
# Jalankan sebagai root: sudo bash setup.sh
# =============================================================================
set -euo pipefail

# ─────────────────────────────────────────────
# Warna & helper
# ─────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()   { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()     { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()   { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()  { echo -e "${RED}[ERROR]${NC} $*" >&2; }
header() { echo -e "\n${BOLD}${CYAN}══════ $* ══════${NC}\n"; }
die()    { error "$*"; exit 1; }

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─────────────────────────────────────────────
# [0] Preflight checks
# ─────────────────────────────────────────────
header "Preflight Checks"

[[ $EUID -eq 0 ]] || die "Script harus dijalankan sebagai root: sudo bash setup.sh"

if [[ -f /etc/os-release ]]; then
  source /etc/os-release
  info "OS: $PRETTY_NAME"
  [[ "$ID" == "ubuntu" || "$ID" == "debian" || "$ID_LIKE" == *"debian"* ]] \
    || warn "Script dioptimasi untuk Ubuntu/Debian."
fi

if command -v docker &>/dev/null; then
  ok "Docker $(docker --version | awk '{print $3}' | tr -d ',') ditemukan"
else
  die "Docker tidak terinstall. Install dulu: https://docs.docker.com/engine/install/"
fi

if docker compose version &>/dev/null 2>&1; then
  ok "Docker Compose $(docker compose version --short 2>/dev/null || echo v2) ditemukan"
  COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
  warn "docker-compose v1 — disarankan upgrade ke Docker Compose Plugin v2"
  COMPOSE_CMD="docker-compose"
else
  die "Docker Compose tidak ditemukan. Install: apt install docker-compose-plugin"
fi

# ─────────────────────────────────────────────
# [1] Install host dependencies
# ─────────────────────────────────────────────
header "Install Host Dependencies"

PKGS_NEEDED=()
for pkg in wireguard wireguard-tools curl jq git; do
  if ! dpkg -s "$pkg" &>/dev/null 2>&1; then
    PKGS_NEEDED+=("$pkg")
  else
    ok "$pkg sudah terinstall"
  fi
done

if [[ ${#PKGS_NEEDED[@]} -gt 0 ]]; then
  info "Menginstall: ${PKGS_NEEDED[*]}"
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y "${PKGS_NEEDED[@]}"
  ok "Package berhasil diinstall"
fi

# ─────────────────────────────────────────────
# [2] Buat data directories
# ─────────────────────────────────────────────
header "Data Directories"

for dir in data/profiles data/artifacts data/state; do
  if [[ ! -d "$REPO_DIR/$dir" ]]; then
    mkdir -p "$REPO_DIR/$dir"
    ok "Dibuat: $dir"
  else
    ok "Sudah ada: $dir"
  fi
done

# ─────────────────────────────────────────────
# [3] Setup .env
# ─────────────────────────────────────────────
header "Konfigurasi Environment (.env)"

ENV_FILE="$REPO_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  ok ".env sudah ada — skip (hapus jika ingin konfigurasi ulang)"
else
  info "Membuat .env baru..."

  # Helper prompt — tulis key=value ke .env
  write_env() {
    local key="$1" val="$2"
    echo "${key}=${val}" >> "$ENV_FILE"
  }

  prompt_env() {
    local key="$1" prompt="$2" default="$3" secret="${4:-no}"
    if [[ "$secret" == "yes" ]]; then
      read -rsp "  $prompt: " val; echo ""
    else
      read -rp  "  $prompt [$default]: " val
    fi
    write_env "$key" "${val:-$default}"
    echo "${val:-$default}"
  }

  echo "# Browser VPS — generated by setup.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$ENV_FILE"
  echo "" >> "$ENV_FILE"

  echo -e "${BOLD}── Database ──────────────────────────────${NC}"
  DB_PASS=$(prompt_env "DB_PASSWORD" "PostgreSQL Password" "$(openssl rand -base64 20)" "yes")
  write_env "DB_ENABLED" "true"

  echo ""
  echo -e "${BOLD}── WireGuard / CHR VPS ───────────────────${NC}"
  prompt_env "CHR_PUBLIC_IP" "IP Publik VPS CHR" "" > /dev/null
  # CHR_PUBLIC_IP hanya untuk referensi setup WireGuard — tidak dipakai oleh compose

  echo ""
  echo -e "${BOLD}── MQTT (CHR Broker) ─────────────────────${NC}"
  read -rp "  Aktifkan MQTT? (y/N): " ENABLE_MQTT
  if [[ "$ENABLE_MQTT" =~ ^[Yy]$ ]]; then
    write_env "MQTT_ENABLED" "true"
    prompt_env "MQTT_BROKER_URL" "MQTT Broker URL" "mqtt://10.10.0.1:1883" > /dev/null
    MQTT_USER=$(prompt_env "MQTT_USERNAME" "MQTT Username" "browser-agent")
    prompt_env "MQTT_PASSWORD" "MQTT Password" "" "yes" > /dev/null
    prompt_env "MQTT_TOPIC_PREFIX" "MQTT Topic Prefix" "scraper/results" > /dev/null
    ok "MQTT dikonfigurasi"
  else
    write_env "MQTT_ENABLED" "false"
    write_env "MQTT_BROKER_URL" "mqtt://10.10.0.1:1883"
    write_env "MQTT_USERNAME" ""
    write_env "MQTT_PASSWORD" ""
    ok "MQTT dinonaktifkan (bisa diaktifkan nanti di .env)"
  fi

  echo ""
  echo -e "${BOLD}── API Security ──────────────────────────${NC}"
  read -rp "  Aktifkan API Key auth? (Y/n): " ENABLE_APIKEY
  if [[ ! "$ENABLE_APIKEY" =~ ^[Nn]$ ]]; then
    API_KEY_VAL=$(openssl rand -hex 32)
    write_env "API_KEY" "$API_KEY_VAL"
    echo ""
    echo -e "  ${BOLD}API Key: ${YELLOW}${API_KEY_VAL}${NC}"
    warn "Simpan API key ini — dibutuhkan oleh VPS CHR (BROWSER_API_KEY)"
  else
    write_env "API_KEY" ""
    ok "API Key auth dinonaktifkan (mode development)"
  fi

  echo ""
  echo -e "${BOLD}── Browser Pool ──────────────────────────${NC}"
  prompt_env "BROWSER_POOL_SIZE" "Jumlah browser slot concurrent" "3" > /dev/null

  ok ".env berhasil dibuat: $ENV_FILE"
fi

# Load .env
set -a; source "$ENV_FILE"; set +a

# ─────────────────────────────────────────────
# [4] Setup WireGuard Client (peer ke VPS CHR)
# ─────────────────────────────────────────────
header "WireGuard Client Setup"

WG_CONF="/etc/wireguard/wg0.conf"

wg_is_active() { wg show wg0 &>/dev/null; }

wg_start() {
  if pidof systemd &>/dev/null && systemctl is-system-running &>/dev/null 2>&1; then
    systemctl enable --now wg-quick@wg0
  else
    wg-quick up wg0
  fi
}

if wg_is_active; then
  ok "WireGuard wg0 sudah berjalan — skip"
  wg show wg0 2>/dev/null | head -4 || true
else
  if [[ -f "$WG_CONF" ]] && ! grep -q "REPLACE_WITH" "$WG_CONF" 2>/dev/null; then
    info "wg0.conf sudah terkonfigurasi, start service..."
    wg_start
    ok "WireGuard dimulai"
  else
    info "Menjalankan wireguard/setup-scraper.sh..."
    bash "$REPO_DIR/wireguard/setup-scraper.sh"
  fi
fi

# Test koneksi ke CHR
if ping -c 1 -W 3 10.10.0.1 &>/dev/null 2>&1; then
  ok "Koneksi ke CHR VPS (10.10.0.1) OK"
else
  warn "Tidak bisa ping 10.10.0.1 — WireGuard mungkin belum terhubung"
  warn "Pastikan Public Key scraper sudah ditambahkan ke VPS CHR"
fi

# ─────────────────────────────────────────────
# [5] Docker Compose — Build & Up
# ─────────────────────────────────────────────
header "Docker Compose — Build & Start"

cd "$REPO_DIR"

info "Build full-tool-browser image (termasuk download Chromium ~300MB)..."
info "Ini bisa memakan waktu 5-10 menit pada build pertama."
$COMPOSE_CMD build --quiet \
  && ok "Build selesai" \
  || die "docker compose build gagal — cek log di atas"

info "Start semua services..."
$COMPOSE_CMD up -d --remove-orphans \
  && ok "Services dimulai" \
  || die "docker compose up gagal"

# Tunggu PostgreSQL dan Redis healthy (max 90 detik)
info "Menunggu PostgreSQL dan Redis healthy..."
WAIT=0
while [[ $WAIT -lt 90 ]]; do
  PG_HEALTH=$($COMPOSE_CMD ps --format json 2>/dev/null \
    | python3 -c "
import json,sys
data=[json.loads(l) for l in sys.stdin if l.strip()]
pg=[d for d in data if d.get('Service')=='postgres']
print(pg[0].get('Health','unknown') if pg else 'unknown')
" 2>/dev/null || echo "unknown")
  REDIS_HEALTH=$($COMPOSE_CMD ps --format json 2>/dev/null \
    | python3 -c "
import json,sys
data=[json.loads(l) for l in sys.stdin if l.strip()]
r=[d for d in data if d.get('Service')=='redis']
print(r[0].get('Health','unknown') if r else 'unknown')
" 2>/dev/null || echo "unknown")

  if [[ "$PG_HEALTH" == "healthy" && "$REDIS_HEALTH" == "healthy" ]]; then
    ok "PostgreSQL healthy"
    ok "Redis healthy"
    break
  fi
  echo -n "."
  sleep 5; WAIT=$((WAIT + 5))
done
echo ""

if [[ $WAIT -ge 90 ]]; then
  warn "Timeout menunggu PostgreSQL/Redis — cek: $COMPOSE_CMD logs postgres redis"
fi

# ─────────────────────────────────────────────
# [6] Validasi
# ─────────────────────────────────────────────
header "Status Akhir"

echo ""
$COMPOSE_CMD ps
echo ""

FAILED=0
for svc in postgres redis full-tool-browser; do
  STATUS=$($COMPOSE_CMD ps --format "{{.Service}} {{.State}}" 2>/dev/null \
    | awk -v s="$svc" '$1==s{print $2}' || echo "unknown")
  if [[ "$STATUS" == "running" ]]; then
    ok "$svc: running"
  else
    error "$svc: ${STATUS:-tidak ditemukan}"
    FAILED=$((FAILED + 1))
  fi
done

# Quick API health check
sleep 3
if curl -sf http://localhost:8080/health &>/dev/null; then
  ok "API health check: OK (http://localhost:8080/health)"
else
  warn "API belum merespons — mungkin masih startup, cek: $COMPOSE_CMD logs full-tool-browser"
fi

echo ""
if [[ $FAILED -eq 0 ]]; then
  echo -e "${GREEN}${BOLD}✔ Setup selesai! Semua services berjalan.${NC}"
else
  echo -e "${YELLOW}${BOLD}⚠ Setup selesai dengan $FAILED service bermasalah.${NC}"
  echo "  Cek log: $COMPOSE_CMD logs <service>"
fi

# ─────────────────────────────────────────────
# [7] Ringkasan akses
# ─────────────────────────────────────────────
header "Ringkasan Akses"

SCRAPER_PUBKEY=""
[[ -f /etc/wireguard/publickey ]] && SCRAPER_PUBKEY=$(cat /etc/wireguard/publickey)

API_KEY_VAL="${API_KEY:-}"
POOL_SIZE="${BROWSER_POOL_SIZE:-3}"

echo -e "  ${BOLD}WireGuard${NC}"
echo "    Interface : wg0  (10.10.0.2/24)"
[[ -n "$SCRAPER_PUBKEY" ]] && echo "    Public Key: $SCRAPER_PUBKEY"
echo "    → Tambahkan Public Key ini ke [Peer] di VPS CHR"
echo ""
echo -e "  ${BOLD}Scraper API${NC}"
echo "    Health    : http://localhost:8080/health"
echo "    Submit job: POST http://localhost:8080/scraper/jobs"
echo "    Analytics : GET  http://localhost:8080/scraper/analytics"
echo "    Monitor   : http://localhost:8080/admin"
echo "    Sessions  : GET  http://localhost:8080/sessions"
if [[ -n "$API_KEY_VAL" ]]; then
  echo ""
  echo -e "  ${BOLD}API Key${NC} (sertakan di setiap request ke VPS CHR)"
  echo "    Header: Authorization: Bearer ${API_KEY_VAL}"
  echo "    → Set BROWSER_API_KEY=${API_KEY_VAL} di VPS CHR docker-compose.yml"
fi
echo ""
echo -e "  ${BOLD}Browser Pool${NC}"
echo "    Slots: $POOL_SIZE concurrent (pool-1 … pool-${POOL_SIZE})"
echo ""
echo -e "  ${BOLD}Langkah selanjutnya${NC}"
echo "    1. Catat WireGuard Public Key Scraper di atas"
echo "    2. Di VPS CHR: tambahkan ke /etc/wireguard/wg0.conf [Peer]"
echo "       PublicKey  = $SCRAPER_PUBKEY"
echo "       AllowedIPs = 10.10.0.2/32"
echo "    3. Reload WireGuard peer di CHR (tanpa downtime):"
echo "       wg set wg0 peer $SCRAPER_PUBKEY allowed-ips 10.10.0.2/32"
if [[ -n "$API_KEY_VAL" ]]; then
  echo "    4. Di VPS CHR docker-compose.yml, set:"
  echo "       BROWSER_API_KEY=${API_KEY_VAL}"
  echo "       lalu: docker compose restart grpc-server"
fi
echo ""
